### Generate data used to test a model or test own stats analysis 

In [1]:
import random 
import numpy as np

In [9]:
# create an array of 10 elements with random values between range 50 - 100 values 
array = []

for i in range(0,10):
    random_data = random.randint(50, 100)
    array.append(random_data) 
    
print(array)
    

[92, 99, 79, 81, 88, 51, 96, 96, 93, 63]


In [16]:
# replace all the odd elements in the array with 0 

for i in range(0,10): 
    if i % 2 == 1:
        array[i] = 0
        
print(array)




[92, 0, 79, 0, 88, 0, 96, 0, 93, 0]


### Homework for 7/10

### 1) Question: Get the positions where elements of a and b match

In [2]:
# create two arrays 
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [20]:
# merge two arrays 
c = np.concatenate((a, b))
c

array([ 1,  2,  3,  2,  3,  4,  3,  4,  5,  6,  7,  2, 10,  2,  7,  4,  9,
        4,  9,  8])

In [21]:
# create one empty list for unique values and one for duplicates. 
uniqueList = []
duplicateList = []

# use for loop
for i in c:
    if i not in uniqueList:
        uniqueList.append(i)
    elif i not in duplicateList:
        duplicateList.append(i)
 
print(duplicateList)

[np.int64(2), np.int64(3), np.int64(4), np.int64(7), np.int64(9)]


### 2) Question: Get all items between 5 and 10 from a.

In [22]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [23]:
values = []

for i in a:
    if i >= 5 and i <= 10:
        values.append(i)
        
print(values)

[np.int64(6), np.int64(9), np.int64(10)]


### 3) Question: Reverse the columns of a 2D array arr.


In [24]:
arr = np.arange(9).reshape(3,3)

In [25]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
# create an empty array where to save values
arr_2 = []

In [36]:
# question: why is it range(len(arr)) and not: for i in arr or for i in range(arr)? 
#what's the difference between the three? 

In [37]:
# loop through arr 1 and append to arr_1

for i in range(len(arr)):
    arr_2.append(arr[i][::-1])

print(arr_2)

[array([2, 1, 0]), array([5, 4, 3]), array([8, 7, 6])]


In [38]:
# print it as an array 
arr_2 = np.array(arr_2)
arr_2

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [ ]:
# how could I invert the rows of the original array instead? 

### 4) Question: Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [63]:
# use methods random and randint to generate random values + .reshape method to specify 
# shape of array 
arr_1 = np.random.randint(5,10, 15).reshape(5,3)
arr_1

array([[7, 9, 5],
       [8, 6, 9],
       [5, 7, 9],
       [6, 8, 8],
       [6, 9, 8]], dtype=int32)

### 5) Question : Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how
### to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


In [68]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]

In [71]:
start = 0
end = len(Z)
step = 4

for i in range(start, end, step):
    x = i
    print(Z[x:x+step])  
    

    

[3, 4, 5, 6]
[7, 8, 9, 10]
[11, 12, 13, 14]


### 6) Question : Find the largest element of the given array.


In [74]:
a = np.array([2, 6, 1, 9, 10, 3, 27, 87, 99, 174 ,2, 5])

In [85]:
# Initialize a variable with smallest possible value 
max_value = arr[0] #start with first element 

# loop through array
for num in a:
    if num > max_value:
        max_value = num

print(max_value)

174


### 7) Find the number of elements in the range 50 - 100.

In [86]:
a = np.array([2, 6, 1, 9, 10, 3, 27, 87, 99, 174 ,2, 5])

In [87]:
values = []

for num in a:
    if num >= 50 and num <= 100:
        values.append(num)

print(values)

[np.int64(87), np.int64(99)]


### 8) Question : Create a 8x8 matrix and fill it with a checkerboard pattern of 0 and 1’s.

In [90]:
# I found an example but I didn't understand 

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 9) Question : Create a 2D array containing random floats between 5 and 10?


In [92]:
arr_1 = np.random.uniform(5,10, 12).reshape(6,2)
arr_1

array([[6.89380746, 8.25849386],
       [7.5380517 , 5.44078605],
       [8.5717836 , 5.17793327],
       [7.24711025, 8.9368586 ],
       [7.04256689, 5.72224236],
       [9.6502166 , 8.44751218]])

### 10) Question: remove the duplicates in the given array. 

In [93]:
a = [ 10 , 20 , 30 , 40, 50, 60, 30 , 30 , 20 , 10 , 80 , 0 , 1 , 220 , 110 , 110, 55 ]

In [95]:
unique_values = np.unique(a)
unique_values

array([  0,   1,  10,  20,  30,  40,  50,  55,  60,  80, 110, 220])